export default {
  ADD_PRODUCT_START: "ADD_PRODUCT_START",
  ADD_PRODUCT_FAILED: "ADD_PRODUCT_FAILED",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAILED: "UPDATE_PRODUCT_FAILED",
  SET_PRODUCTS_SUCCESS: "SET_PRODUCTS_SUCCESS",
  SET_PRODUCTS_FAILED: "SET_PRODUCTS_FAILED",
  SET_PRODUCTS_START: "SET_PRODUCTS_START",
  REMOVE_PRODUCTS_SUCCESS: "REMOVE_PRODUCTS_SUCCESS",
  REMOVE_PRODUCTS_FAILED: "REMOVE_PRODUCTS_FAILED",
};
