export default {
  PROCCESS_ORDER_START: "PROCCESS_ORDER_START",
  PROCCESS_ORDER_FAILED: "PROCCESS_ORDER_FAILED",
  ADD_ORDER_SUCCESS: "ADD_ORDER_SUCCESS",
  FETCH_ORDERS_SUCCESS: "FETCH_ORDERS_SUCCESS",
};
