export default {
  AUTHENTICATE_USER_START: "AUTHENTICATE_USER_START",
  AUTHENTICATE_USER_SUCCESS: "AUTHENTICATE_USER_SUCCESS",
  AUTHENTICATE_USER_FAILED: "AUTHENTICATE_USER_FAILED",
  USER_LOGOUT: "USER_LOGOUT",
};
